//try error
public class Main {
    public static void main(String[] args) {
        int[] myNumbers = (1, 2, 3);
        System.out.println(myNumbers(10));
    }
}

//usage of finally

public class Main{
    public static void main(String[] args)
    {
        try{
            int[] myNumber ={1,2,3};
            System.out.println(myNumber[10]);
        }
        catch(Exception e){
            System.out.println("something went wrong");
        }finally{
            System.out.println(" the 'try catch'is finsished:");
        }
    }
}
